"""empty message

Revision ID: e7d796d0ce32
Revises: 2de8334beaf4
Create Date: 2024-12-04 14:08:36.141426

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e7d796d0ce32"
down_revision: Union[str, None] = "2de8334beaf4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contest_result",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("problem_is_solved", sa.Boolean(), nullable=False),
        sa.Column("penalty_time", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("problem_id", sa.Uuid(), nullable=False),
        sa.Column("contest_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["contest_id"],
            ["contest.id"],
        ),
        sa.ForeignKeyConstraint(
            ["problem_id"],
            ["problem.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "problem",
        sa.Column("is_public", sa.Boolean(), nullable=False, server_default="t"),
    )
    op.drop_column("problem", "is_in_contest")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "problem",
        sa.Column(
            "is_in_contest",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
            server_default="f",
        ),
    )
    op.drop_column("problem", "is_public")
    op.drop_table("contest_result")
    # ### end Alembic commands ###
