"""empty message

Revision ID: a921441e8635
Revises: e7d796d0ce32
Create Date: 2025-02-03 19:25:57.971205

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a921441e8635"
down_revision: Union[str, None] = "e7d796d0ce32"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profile",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("avatar_url", sa.String(), nullable=True),
        sa.Column("activity_calendar", sa.JSON(), nullable=True),
        sa.Column("passed_contests", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "problem",
        "is_public",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "problem",
        "is_public",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        existing_nullable=False,
    )
    op.drop_table("profile")
    # ### end Alembic commands ###
